# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'demoRadioButton2.ui'
#
# Created by: PyQt5 UI code generator 5.15.1
#
# WARNING: Any manual changes made to this file will be lost when pyuic5 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt5 import QtCore, QtGui, QtWidgets


class Ui_Dialog(object):
    def setupUi(self, Dialog):
        Dialog.setObjectName("Dialog")
        Dialog.resize(834, 564)
        self.verticalLayoutWidget = QtWidgets.QWidget(Dialog)
        self.verticalLayoutWidget.setGeometry(QtCore.QRect(110, 80, 131, 221))
        self.verticalLayoutWidget.setObjectName("verticalLayoutWidget")
        self.verticalLayout = QtWidgets.QVBoxLayout(self.verticalLayoutWidget)
        self.verticalLayout.setContentsMargins(0, 0, 0, 0)
        self.verticalLayout.setObjectName("verticalLayout")
        self.radioButtonLarge = QtWidgets.QRadioButton(self.verticalLayoutWidget)
        self.radioButtonLarge.setObjectName("radioButtonLarge")
        self.verticalLayout.addWidget(self.radioButtonLarge)
        self.radioButtonMedium = QtWidgets.QRadioButton(self.verticalLayoutWidget)
        self.radioButtonMedium.setObjectName("radioButtonMedium")
        self.verticalLayout.addWidget(self.radioButtonMedium)
        self.radioButtonXL = QtWidgets.QRadioButton(self.verticalLayoutWidget)
        self.radioButtonXL.setObjectName("radioButtonXL")
        self.verticalLayout.addWidget(self.radioButtonXL)
        self.radioButtonXXL = QtWidgets.QRadioButton(self.verticalLayoutWidget)
        self.radioButtonXXL.setObjectName("radioButtonXXL")
        self.verticalLayout.addWidget(self.radioButtonXXL)
        self.horizontalLayoutWidget = QtWidgets.QWidget(Dialog)
        self.horizontalLayoutWidget.setGeometry(QtCore.QRect(109, 380, 511, 71))
        self.horizontalLayoutWidget.setObjectName("horizontalLayoutWidget")
        self.horizontalLayout = QtWidgets.QHBoxLayout(self.horizontalLayoutWidget)
        self.horizontalLayout.setContentsMargins(0, 0, 0, 0)
        self.horizontalLayout.setObjectName("horizontalLayout")
        self.radioButtonDebitCard = QtWidgets.QRadioButton(self.horizontalLayoutWidget)
        self.radioButtonDebitCard.setObjectName("radioButtonDebitCard")
        self.horizontalLayout.addWidget(self.radioButtonDebitCard)
        self.radioButtonNetBanking = QtWidgets.QRadioButton(self.horizontalLayoutWidget)
        self.radioButtonNetBanking.setObjectName("radioButtonNetBanking")
        self.horizontalLayout.addWidget(self.radioButtonNetBanking)
        self.radioButtonCash = QtWidgets.QRadioButton(self.horizontalLayoutWidget)
        self.radioButtonCash.setObjectName("radioButtonCash")
        self.horizontalLayout.addWidget(self.radioButtonCash)
        self.label = QtWidgets.QLabel(Dialog)
        self.label.setGeometry(QtCore.QRect(110, 30, 371, 31))
        self.label.setObjectName("label")
        self.label_2 = QtWidgets.QLabel(Dialog)
        self.label_2.setGeometry(QtCore.QRect(110, 330, 231, 31))
        self.label_2.setObjectName("label_2")
        self.labelSelected = QtWidgets.QLabel(Dialog)
        self.labelSelected.setGeometry(QtCore.QRect(110, 490, 521, 41))
        self.labelSelected.setObjectName("labelSelected")

        self.retranslateUi(Dialog)
        QtCore.QMetaObject.connectSlotsByName(Dialog)

    def retranslateUi(self, Dialog):
        _translate = QtCore.QCoreApplication.translate
        Dialog.setWindowTitle(_translate("Dialog", "Dialog"))
        self.radioButtonLarge.setText(_translate("Dialog", "L"))
        self.radioButtonMedium.setText(_translate("Dialog", "M"))
        self.radioButtonXL.setText(_translate("Dialog", "XL"))
        self.radioButtonXXL.setText(_translate("Dialog", "XXL"))
        self.radioButtonDebitCard.setText(_translate("Dialog", "Debit Card"))
        self.radioButtonNetBanking.setText(_translate("Dialog", "net banking"))
        self.radioButtonCash.setText(_translate("Dialog", "Cash On Delivery"))
        self.label.setText(_translate("Dialog", "select the shirt size"))
        self.label_2.setText(_translate("Dialog", "Chosse your Payment Method"))
        self.labelSelected.setText(_translate("Dialog", "TextLabel"))
