# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'demoSlider.ui'
#
# Created by: PyQt5 UI code generator 5.15.1
#
# WARNING: Any manual changes made to this file will be lost when pyuic5 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt5 import QtCore, QtGui, QtWidgets


class Ui_Dialog(object):
    def setupUi(self, Dialog):
        Dialog.setObjectName("Dialog")
        Dialog.resize(617, 431)
        self.label = QtWidgets.QLabel(Dialog)
        self.label.setGeometry(QtCore.QRect(70, 50, 91, 16))
        self.label.setObjectName("label")
        self.label_2 = QtWidgets.QLabel(Dialog)
        self.label_2.setGeometry(QtCore.QRect(70, 90, 121, 16))
        self.label_2.setObjectName("label_2")
        self.label_3 = QtWidgets.QLabel(Dialog)
        self.label_3.setGeometry(QtCore.QRect(70, 140, 111, 16))
        self.label_3.setObjectName("label_3")
        self.label_4 = QtWidgets.QLabel(Dialog)
        self.label_4.setGeometry(QtCore.QRect(310, 140, 111, 21))
        self.label_4.setObjectName("label_4")
        self.horizontalScrollBarSugerlevel = QtWidgets.QScrollBar(Dialog)
        self.horizontalScrollBarSugerlevel.setGeometry(QtCore.QRect(250, 50, 160, 16))
        self.horizontalScrollBarSugerlevel.setOrientation(QtCore.Qt.Horizontal)
        self.horizontalScrollBarSugerlevel.setObjectName("horizontalScrollBarSugerlevel")
        self.verticalScrollBarPulseRate = QtWidgets.QScrollBar(Dialog)
        self.verticalScrollBarPulseRate.setGeometry(QtCore.QRect(190, 130, 16, 160))
        self.verticalScrollBarPulseRate.setOrientation(QtCore.Qt.Vertical)
        self.verticalScrollBarPulseRate.setObjectName("verticalScrollBarPulseRate")
        self.horizontalSliderbloodPressure = QtWidgets.QSlider(Dialog)
        self.horizontalSliderbloodPressure.setGeometry(QtCore.QRect(250, 90, 160, 22))
        self.horizontalSliderbloodPressure.setOrientation(QtCore.Qt.Horizontal)
        self.horizontalSliderbloodPressure.setObjectName("horizontalSliderbloodPressure")
        self.verticalSliderCholestorol = QtWidgets.QSlider(Dialog)
        self.verticalSliderCholestorol.setGeometry(QtCore.QRect(410, 140, 22, 160))
        self.verticalSliderCholestorol.setOrientation(QtCore.Qt.Vertical)
        self.verticalSliderCholestorol.setObjectName("verticalSliderCholestorol")
        self.lineEditResult = QtWidgets.QLineEdit(Dialog)
        self.lineEditResult.setGeometry(QtCore.QRect(180, 360, 341, 31))
        self.lineEditResult.setObjectName("lineEditResult")

        self.retranslateUi(Dialog)
        QtCore.QMetaObject.connectSlotsByName(Dialog)

    def retranslateUi(self, Dialog):
        _translate = QtCore.QCoreApplication.translate
        Dialog.setWindowTitle(_translate("Dialog", "Dialog"))
        self.label.setText(_translate("Dialog", "Sugar Level"))
        self.label_2.setText(_translate("Dialog", "Blood pressure"))
        self.label_3.setText(_translate("Dialog", "pulse rate"))
        self.label_4.setText(_translate("Dialog", "cholestorol"))
