# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'demoListWidget1.ui'
#
# Created by: PyQt5 UI code generator 5.15.1
#
# WARNING: Any manual changes made to this file will be lost when pyuic5 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt5 import QtCore, QtGui, QtWidgets


class Ui_Dialog(object):
    def setupUi(self, Dialog):
        Dialog.setObjectName("Dialog")
        Dialog.resize(841, 542)
        self.listWidgetDiagnosisTest = QtWidgets.QListWidget(Dialog)
        self.listWidgetDiagnosisTest.setGeometry(QtCore.QRect(420, 60, 256, 192))
        self.listWidgetDiagnosisTest.setSelectionMode(QtWidgets.QAbstractItemView.MultiSelection)
        self.listWidgetDiagnosisTest.setObjectName("listWidgetDiagnosisTest")
        item = QtWidgets.QListWidgetItem()
        self.listWidgetDiagnosisTest.addItem(item)
        item = QtWidgets.QListWidgetItem()
        self.listWidgetDiagnosisTest.addItem(item)
        item = QtWidgets.QListWidgetItem()
        self.listWidgetDiagnosisTest.addItem(item)
        item = QtWidgets.QListWidgetItem()
        self.listWidgetDiagnosisTest.addItem(item)
        self.listWidgetSelectedTest = QtWidgets.QListWidget(Dialog)
        self.listWidgetSelectedTest.setGeometry(QtCore.QRect(420, 300, 256, 192))
        self.listWidgetSelectedTest.setObjectName("listWidgetSelectedTest")
        self.label = QtWidgets.QLabel(Dialog)
        self.label.setGeometry(QtCore.QRect(100, 80, 131, 41))
        self.label.setObjectName("label")
        self.label_2 = QtWidgets.QLabel(Dialog)
        self.label_2.setGeometry(QtCore.QRect(100, 320, 161, 41))
        self.label_2.setObjectName("label_2")

        self.retranslateUi(Dialog)
        QtCore.QMetaObject.connectSlotsByName(Dialog)

    def retranslateUi(self, Dialog):
        _translate = QtCore.QCoreApplication.translate
        Dialog.setWindowTitle(_translate("Dialog", "Dialog"))
        __sortingEnabled = self.listWidgetDiagnosisTest.isSortingEnabled()
        self.listWidgetDiagnosisTest.setSortingEnabled(False)
        item = self.listWidgetDiagnosisTest.item(0)
        item.setText(_translate("Dialog", "urine Analysis $5"))
        item = self.listWidgetDiagnosisTest.item(1)
        item.setText(_translate("Dialog", "X Ray $100"))
        item = self.listWidgetDiagnosisTest.item(2)
        item.setText(_translate("Dialog", "Doppler $7"))
        item = self.listWidgetDiagnosisTest.item(3)
        item.setText(_translate("Dialog", "homoglobin $4"))
        self.listWidgetDiagnosisTest.setSortingEnabled(__sortingEnabled)
        self.label.setText(_translate("Dialog", "Diagnosis Tests "))
        self.label_2.setText(_translate("Dialog", "Selected Tests "))
