# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'demoCheckBox1.ui'
#
# Created by: PyQt5 UI code generator 5.15.1
#
# WARNING: Any manual changes made to this file will be lost when pyuic5 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt5 import QtCore, QtGui, QtWidgets


class Ui_Dialog(object):
    def setupUi(self, Dialog):
        Dialog.setObjectName("Dialog")
        Dialog.resize(827, 535)
        self.label = QtWidgets.QLabel(Dialog)
        self.label.setGeometry(QtCore.QRect(130, 30, 311, 41))
        font = QtGui.QFont()
        font.setPointSize(16)
        self.label.setFont(font)
        self.label.setObjectName("label")
        self.label_2 = QtWidgets.QLabel(Dialog)
        self.label_2.setGeometry(QtCore.QRect(130, 130, 181, 61))
        font = QtGui.QFont()
        font.setPointSize(14)
        self.label_2.setFont(font)
        self.label_2.setObjectName("label_2")
        self.labelAmount = QtWidgets.QLabel(Dialog)
        self.labelAmount.setGeometry(QtCore.QRect(130, 450, 571, 51))
        font = QtGui.QFont()
        font.setPointSize(14)
        self.labelAmount.setFont(font)
        self.labelAmount.setObjectName("labelAmount")
        self.checkBoxCheese = QtWidgets.QCheckBox(Dialog)
        self.checkBoxCheese.setGeometry(QtCore.QRect(470, 120, 241, 17))
        font = QtGui.QFont()
        font.setPointSize(14)
        self.checkBoxCheese.setFont(font)
        self.checkBoxCheese.setObjectName("checkBoxCheese")
        self.checkBoxOlive = QtWidgets.QCheckBox(Dialog)
        self.checkBoxOlive.setGeometry(QtCore.QRect(470, 170, 231, 17))
        font = QtGui.QFont()
        font.setPointSize(14)
        self.checkBoxOlive.setFont(font)
        self.checkBoxOlive.setObjectName("checkBoxOlive")
        self.checkBoxSausege = QtWidgets.QCheckBox(Dialog)
        self.checkBoxSausege.setGeometry(QtCore.QRect(470, 220, 211, 17))
        font = QtGui.QFont()
        font.setPointSize(14)
        self.checkBoxSausege.setFont(font)
        self.checkBoxSausege.setObjectName("checkBoxSausege")

        self.retranslateUi(Dialog)
        QtCore.QMetaObject.connectSlotsByName(Dialog)

    def retranslateUi(self, Dialog):
        _translate = QtCore.QCoreApplication.translate
        Dialog.setWindowTitle(_translate("Dialog", "Dialog"))
        self.label.setText(_translate("Dialog", "Regular Pizza $10"))
        self.label_2.setText(_translate("Dialog", "select your toppings"))
        self.labelAmount.setText(_translate("Dialog", "TextLabel"))
        self.checkBoxCheese.setText(_translate("Dialog", "Extra Cheese $1"))
        self.checkBoxOlive.setText(_translate("Dialog", "Extra Olive $2"))
        self.checkBoxSausege.setText(_translate("Dialog", "Extra Sausage $1"))
